version: '3.8'

services:

    example-frontend:
      image: example-frontend:latest
      container_name: example-frontend
      build: ./example-frontend
      ports:
        - 5000:5000

    example-backend:
      image: example-backend:latest
      container_name: example-backend
      build: ./example-backend
      ports:
        - 8080:8080

# Run:
# docker compose up
#   - Go to "http://localhost:5000"
#   - Press button of Exercise 1.14 
