version: '3.8'

services:

    example-frontend:
      image: example-frontend:latest
      container_name: example-frontend
      build: ./example-frontend
      ports:
        - 5000:5000

    example-backend:
      image: example-backend:latest
      container_name: example-backend
      build: ./example-backend
      ports:
        - 8080:8080
      environment:    # --> This tells backend service to connect to Redis database
        - REDIS_HOST=redis  
      depends_on:
        - redis       # --> Ensure that the redis service starts before the backend service
    
    redis:
      image: redis

# Run:
# docker compose up
#   - Go to "http://localhost:5000"
#   - Press button of Exercise 2.4 

# REDIS_HOST has been added to Dockerfile of example-backend 

# By default Compose sets up a single network for your app. Each container
# for a service joins the default network and is both reachable by other
# containers on that network, and discoverable by them at a hostname identical
# to the container name.
