version: '3.8'   # --- Compose file format. Just informative. It can be omitted.

services:        # --- Only means you declare your services (which are your containers)

    youtube-dl-ubuntu:   # --- This is your service ID (you can put whatever you want here)
      container_name: youtube-dl       # --- It's the name of the container
      image: youtube-dl:latest         # --- It's the name of the image
      build: .                         # --- Path to Dockerfie
      volumes:                         # --- Volume section (container to local)
        - .:/mydir                     # --- (pwd) from local to /mydir of the container

# Run a one-off command on a service:
# docker compose run youtube-dl-ubuntu https://imgur.com/JY5tHqr
# ^ unless you want to override a command or running only one container 
#   on different ports, "docker-compose up" (even for one container) is enough.


# Your Docker workflow should be to build a suitable Dockerfile for each image
# you wish to create, then use compose to assemble the images using the build 
# command. 

# Docker Compose will use the Dockerfile if you add the build command to your 
# project's compose.yaml. If your compose.yaml uses a public image (pulling 
# image from the docker hub), then you don't need a Dockerfile


